services:
  backend:
    build: ./MVP_Backend
    container_name: mvp_backend
    ports:
      - "5000:5000"
    volumes:
      - ./MVP_Backend:/app
    restart: unless-stopped

  frontend:
    build: ./MVP_Frontend
    container_name: mvp_frontend
    ports:
      - "3000:80"
    volumes:
      - ./MVP_Frontend:/usr/share/nginx/html
    depends_on:
      - backend
    restart: unless-stopped
